---
title: "Knight-Hennessy Scholarship To-Dos"
author: "Fabio Votta"
date: "19.7.2018"
output: pdf_document
---

**The deadline to submit your graduate degree program application is November 14, 2018.**

## Academic Interests

1. Briefly describe your research interests in the PhD field (Social Sciences - Political Science PhD)


*750 characters remaining*

2. List up to three Stanford faculty members whose research interests best align with yours and who could serve as potential research advisors.


## Work Experience

Please share some information about your internships and work experience (full-time and part-time) in the space below. These experiences give you the chance to learn about yourself and about working with others, and to apply your knowledge.

If you've had more than one role at the same organization, then please list that organization once. We can tell by the starting and ending positions that you've changed roles.
Report the full-time annualized compensation. For instance, if you have an internship that pays $10/hour, then the annualized compensation is $10/hour x 40 hours/week x 50 work weeks/year = $20,000.
If you need to convert your compensation to $U.S., then please use the same currency conversion scale for starting and ending compensation.


## Activities and Interests


We want to understand what you care about and how you spend your time outside of the classroom or the office. Please list up to three community, extracurricular, personal, or volunteer activities and/or interests in order of significance to you (i.e., item #1 on the list should be the activity or interest that matters most to you).

If there are additional activities you wish to tell us about, feel free to include them on your resumé.

## Standardized Test Scores


Please list the results of any standardized test recommended or required by your graduate degree program — e.g., GMAT for the MBA Program, GRE (some departments also will recommend or require subject tests), LSAT for the JD Program, MCAT for the MD Program. If you are not required to submit standardized test scores for your degree program application, then you do not need to list scores on this page.

If English is not your first language, you also may be required to submit the results from an approved English proficiency exam. All Stanford graduate programs accept the TOEFL, and the MBA Program also accepts the IELTS and PTE. For more details on this requirement, please refer to the Graduate Admissions website (TOEFL) or MBA Admission website (TOEFL, IELTS, or PTE).

Your unofficial scores will suffice for the Knight-Hennessy Scholars program. While it's helpful and preferred if you have your test scores by the time you apply to the Knight-Hennessy Scholars program, this is not a requirement. You must, however, have any required test scores by the departmental deadline.

Please ensure that your scores are valid for your graduate department application. In general:

GMAT, GRE, and LSAT scores are valid for five years.
MCAT scores are valid for three years.
TOEFL scores are valid for 18 months for most graduate degree programs at Stanford.

## Resumé

Your one-page resumé frames your intellectual, personal, and professional background and accomplishments. It may include information that is duplicated in other sections of your application (e.g., Academics, Employment, Activities, Awards). Think of the resume as a framework for the detailed information that we'll read in those sections.

Our rule of thumb is one page for every decade of work experience. If you’ve worked more than a decade, then feel free to add a page to your resumé for additional context and depth. Otherwise, please stick to one page.

## Recommendation Letters

Your letters of reference provide a different perspective on your abilities and accomplishments. The best letters add depth to an application and bring candidates to life. They highlight the very strongest candidates from a pool of many well-qualified applicants. They focus on aspects of your character and potential that may be difficult to glean from your application.

Two letters of recommendation must be submitted by the application deadline:
September 12, 2018 at 1:00pm Pacific Time
Register your two recommenders at the bottom of this page as early in the application process as possible.

### Choose Your Recommenders

Select two recommenders who know you well, whose opinions you trust, and who want to see you succeed. These individuals must be able to provide specific examples, anecdotes, and evidence of your ability and determination to make a difference. Here are a few things to consider as you choose recommenders:

In general, we care about the content of the letter, not the title or position of the person who wrote it.
Your Knight-Hennessy Scholars recommendations are the only reference letters that we will review before we provide input to your graduate program.
Once your graduate program shares its feedback with Knight-Hennessy Scholars, we also will review your departmental recommendation letters. As such, your recommendation choices for the Knight-Hennessy Scholars program should make a compelling independent case, and also complement the references of your graduate program.
It's fine to ask the same person to provide recommendations for your graduate program and for Knight-Hennessy Scholars, but ensure that he/she submits distinctive letters of reference that address the questions each application requires.
We ask your recommenders to assess some character and leadership traits in the reference letters, and to address the following:

*1. Please explain how you know and interact with the applicant.*

*2. Please tell us about a time the applicant did something that benefited others.*

*3. Please tell us about a time the applicant faced adversity.*

*4. Please tell us about a time the applicant surprised you.*

*5. Is there anything else that we should know about the applicant?*


## Essays and Short Answers

Through other facets of your Knight-Hennessy Scholars application — your academic history, work experience, activities and interests, awards, etc. — we learn a great deal about what you have done. The essays are not the place to repeat those things. Instead, the goal of posing these questions is to require you to engage in disciplined reflection to tell a story that only you can tell.

### Essays

Please respond to the two required essay questions using the provided text boxes below. The length of both essays combined should not exceed 1,750 words (e.g., if your response for Essay 1 is 1,000 words, this leaves 750 words for Essay 2).

1. Essay 1: Connect the dots. How have the influences in your life shaped you?
You may find it helpful to review the 2005 Stanford Commencement address delivered by Steve Jobs.

This essay is the ideal space to share how you became an independent thinker, courageous dissenter, ambitious and tenacious leader, and kind civic activist. Do not describe your actions alone: go in depth about your fears, your frustrations, your doubts, and the voice that ran in your head to guide those actions. These are the keys to revealing how you have been shaped and making a deep impression on the admission committee.


2. Essay 2: How will you pursue your life's calling? How will your Stanford education and your Knight-Hennessy Scholars experience support this?

Last year’s application phrased the question differently but pointed applicants to the Designing Your Life work of Stanford Professors Bill Burnett and Dave Evans. I still think that suggestion is relevant since Burnett and Evans’ work guides people through the process of thinking about and pursuing their callings to achieve fulfilled lives.

This essay can reveal much more than pipe dreams for the future if you share the ways in which you have already made inroads in some of your fields of interest and the passion that drove you in each. What risks did you take? What preconceived notions did you have to throw out so that you could pursue these passions? What failures pointed you in better directions? What creative solutions have you devised that effected lasting change? How will Stanford and the Knight-Hennessy Scholarship help you build on these experiences to even larger impacts?

http://lifedesignlab.stanford.edu/

*Writing About Resilience in the Face of Failure*

https://blog.accepted.com/writing-about-resilience-in-the-face-of-failure/

### Short Answers

1. Short Answer 1: Please tell us **eight improbable facts** (things that are unlikely but true) about you.

For your eight improbable facts, you may write a total of 150 words (an average of around 18 words each). Since the application form offers you space to discuss your three most meaningful activities and three most significant awards (see the next question), this space is best dedicated to more unique aspects of your background. If you’re having trouble with this one, you may find it helpful to kickstart your brainstorming process by talking to your friends and family about things they find unusual about you.


2. Short Answer 2: Please list three goals/objectives that you are working toward right now. (No, being admitted to Stanford and/or being selected as a Knight-Hennessy Scholar can't count as one of those goals.)*

All three current goals/objectives can only total 75 words, so you’ll need to be brief in your descriptions. Ideally, you will be able to illustrate your ambition, tenacity, purposeful leadership, civic action or kindness with each of these. If you’ve been perfecting your Cruyff Turn in soccer, building your fluency in Mandarin, or driving civic engagement among a disaffected community, then you have great material for this short answer question.

## Video

Although we cannot meet in-person with each applicant to the Knight-Hennessy Scholars program, we invite you to submit a video that gives us a chance to "meet" you. There is no attention — zero emphasis! — on the "production value" of your video.

You can certainly write a script for this video in advance of recording; however, you must record it live within the online application. Don’t worry, you can re-record your video up to nine times if you stutter or lose your place. Your video may last up to two minutes, but you can press Stop Recording earlier if your script does not fill the entire allotted time. Your topic can be anything, but the best lessons will share something you know well and are passionate about: anything from guitar or Tai Chi to the engineering of bridges. The point is to give the admissions committee a sense of your voice, your verbal communication, and, if possible, your personality.

## Additional Information

While we believe that we get to know you well through your application, we recognize that no application can fully capture all elements of your life.

You may feel free to use the space below to share essential information not conveyed elsewhere in your application (e.g., a factor affecting your academic performance).


If there is something important that just didn’t fit anywhere else, you have 750 characters to share it here. That’s approximately six sentences.

## Good Resources

- https://blog.accepted.com/stanford-knight-hennessy-scholars-program-application/