---
title: "PhD at Harvard University"
author: "Fabio Votta"
date: "19.7.2018"
output: pdf_document
---

## Application

### 0. Deadlines and Fees

APPLICATION DEADLINE
December 15, 2018
Deadline 5 p.m. Eastern Time

Online application form and fee payment ($105)

### 1. Statement of Academic Purpose

The statement of purpose is very important to programs when deciding whether to admit a candidate. Your statement should be focused, informative, and convey your research interests and qualifications. You should provide a vivid picture of your intellectual profile: how you formulate research topics, how you pursue them, and how you articulate any interesting findings. As you convey this information, it is important to emphasize how these experiences have influenced both your decision to undertake graduate study and your goals within a graduate program.

### 2. Recommendation Letters

Before applying, confirm that **three faculty members or others qualified** to evaluate your potential for graduate study have agreed to **submit letters of recommendation** on your behalf. At least one letter should be from a faculty member at the school where you earned your most recent degree, unless you have been out of school for more than five years.

You must provide the e-mail addresses of three recommenders when you apply. GSAS requires your recommenders to submit their letters via an online recommendation system. By law, enrolled students have the right to view their letters of recommendation, unless they indicate otherwise at the time of application. Please note on your application whether you are waiving your right to see these letters. Learn more about your right to inspect letters of recommendation.

We regret that we are unable to accept letters submitted through a recommendation dossier service.

All letters of recommendation are due at the same time as the application. While GSAS will make every effort to ensure consideration of information submitted after the deadline, we cannot ensure that it will be used in the evaluation of your application.

### 3. Transcripts

Applicants are required to upload transcript copies from each college/university they attended into our online application system: official hard copy/paper transcripts are not required at the time of application. 

Please note that transcripts from international institutions—records of all courses, seminars, and examinations, including grades, scores, grading scales, and confirmation of degree conferral—must be in English. If records are not available in English, original records must be accompanied by certified English translations. All translations must be literal and complete versions of the original records.

For those applicants currently enrolled in a college or university, GSAS does not require submission of fall grades. Should you wish to update your submitted application with fall grades, you may do so using the Fall Grade Report section of the online application. While GSAS will make every effort to ensure consideration of information submitted after the deadline, we cannot ensure that it will be used in the evaluation of your application.

### 5. TOEFL

Adequate command of spoken and written English is essential to success in graduate study at Harvard. Applicants who are non-native English speakers and who received their undergraduate degree from an academic institution where English is not the primary language of instruction must take the Internet based test (iBT) of the Test of English as a Foreign Language (TOEFL), administered by the Educational Testing Service (ETS). A minimum score of 80 is required, but some programs may require a higher score. Applicants who took the TOEFL more than two years ago (i.e. before September 1, 2016, for fall 2018 admission) must retake the test. No test other than the iBT TOEFL will be accepted as proof of English proficiency; a master's degree is not accepted as proof of English proficiency.

Applicants must request that ETS send an official score report to the Harvard University Graduate School of Arts and Sciences using code 3451. If you have a copy of your Score Confirmation Report, you can upload it to your online application for consideration by the admissions committee. However, you will still need to ensure that Educational Testing Service sends an official score report.

TOEFL Account:

Rashnutin

Start Time:   10:00 AM			
Saturday, September 29, 2018			
STUTTGART, BW, Germany

### 6. GRE (Graduate Record Examination)

Many GSAS programs require that prospective students present scores of the General Test of the Graduate Record Examinations (GRE). Scores from either the computer-delivered or the paper-delivered test are acceptable. Many programs also require one of the GRE Subject Tests. Visit the relevant department in the Programs of Study for more information.

It is essential that you arrange to take the GRE in sufficient time for score reports to reach us by the application deadline. GRE scores are valid for five years (i.e. scores must be from no earlier than September 1, 2012, for fall 2018 admission). If you have personal score reports available from tests taken within the last five years, you can upload them to your online application for consideration by the admissions committee. However, you will still need to ensure that Educational Testing Service (ETS) sends an official score report. Be sure to register for the tests well before administration dates and request that your scores be sent to Harvard University Graduate **School of Arts and Sciences** using code **3451**.

GRE Account:

favstats

Test Center: Frankfurt
Date: Pretty much every day
Costs: 205$

### 7. Writing Sample

The department requires the submission of a writing sample. This should be a recent scholarly or critical paper double-spaced and no more than 20 pages.

## Important People
