---
title: "PhD at Harvard University"
author: "Fabio Votta"
date: "19.7.2018"
output: pdf_document
---

## Application

### 0. Deadlines and Fees

The deadline to apply for admission for the academic year 2019-20 is 11:59pm (Pacific time) on December 4, 2018. No late applications will be accepted. The application for admission for the academic year 2019-20 will open in September 2018. 

Application fee of $125

### 1. Statement of Academic Purpose

The Statement of Purpose should describe succinctly your reasons for applying to the proposed program at Stanford, your preparation for this field of study, research interests, future career plans, and other aspects of your background and interests which may aid the admissions committee in evaluating your aptitude and motivation for graduate study. The Statement of Purpose should not exceed two single spaced pages.

### 2. Recommendation Letters

Before applying, confirm that **three faculty members or others qualified** to evaluate your potential for graduate study have agreed to **submit letters of recommendation** on your behalf. At least one letter should be from a faculty member at the school where you earned your most recent degree, unless you have been out of school for more than five years.

You must provide the e-mail addresses of three recommenders when you apply. GSAS requires your recommenders to submit their letters via an online recommendation system. By law, enrolled students have the right to view their letters of recommendation, unless they indicate otherwise at the time of application. Please note on your application whether you are waiving your right to see these letters. Learn more about your right to inspect letters of recommendation.

We regret that we are unable to accept letters submitted through a recommendation dossier service.

All letters of recommendation are due at the same time as the application. While GSAS will make every effort to ensure consideration of information submitted after the deadline, we cannot ensure that it will be used in the evaluation of your application.

### 3. Transcripts

Applicants are required to upload transcript copies from each college/university they attended into our online application system: official hard copy/paper transcripts are not required at the time of application. 

Please note that transcripts from international institutions—records of all courses, seminars, and examinations, including grades, scores, grading scales, and confirmation of degree conferral—must be in English. If records are not available in English, original records must be accompanied by certified English translations. All translations must be literal and complete versions of the original records.

For those applicants currently enrolled in a college or university, GSAS does not require submission of fall grades. Should you wish to update your submitted application with fall grades, you may do so using the Fall Grade Report section of the online application. While GSAS will make every effort to ensure consideration of information submitted after the deadline, we cannot ensure that it will be used in the evaluation of your application.

### 5. TOEFL

Yes

TOEFL Account:

Rashnutin

Start Time:   10:00 AM			
Saturday, September 29, 2018			
STUTTGART, BW, Germany

### 6. GRE (Graduate Record Examination)

Yes

GRE Account:

favstats

Test Center: Frankfurt
Date: Pretty much every day
Costs: 205$

### 7. Writing Sample

The department requires the submission of a writing sample. This should be a recent scholarly or critical paper double-spaced and no more than 20 pages.

## Important People
